apiVersion: apps/v1
kind: Deployment
metadata:
  name: studio-api-grpc-prompt2vector
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api
          image: app_image
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: studio-api-grpc-prompt2vector-cm
          ports:
            - name: grpc
              containerPort: 8081
          readinessProbe:
            failureThreshold: 3
            exec:
              command: ["/bin/grpc_health_probe", "-addr=localhost:8081"]
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 30         
          livenessProbe:
            failureThreshold: 3
            exec:
              command: ["/bin/grpc_health_probe", "-addr=localhost:8081"]
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 30
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
