apiVersion: v1
kind: ConfigMap
metadata:
  name: studio-api-grpc-prompt2vector-telegraf-cm
data:
  telegraf.conf: |
    [agent]
    flush_interval = "5s"
    round_interval = true
    omit_hostname = true
    interval = "5s"
    debug = false

    [[inputs.prometheus]]
    ## An array of urls to scrape metrics from.
    urls = ["http://localhost:3000/metrics"]
    interval = "1s"
    metric_version = 2

    [[inputs.cpu]]
    ## Whether to report per-cpu stats or not
    percpu = true
    ## Whether to report total system cpu stats or not
    totalcpu = true
    ## If true, collect raw CPU time metrics
    collect_cpu_time = false
    ## If true, compute and report the sum of all non-idle CPU states
    report_active = false

    [[inputs.mem]]

    [[inputs.processes]]

    [[outputs.prometheus_client]]
    listen = ":9126"
    metric_version = 2
    collectors_exclude = ["gocollector", "process"]
