# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedded_encode.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'embedded_encode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65mbedded_encode.proto\"$\n\x0f\x45ncodingRequest\x12\x11\n\tsentences\x18\x01 \x03(\t\"\x1c\n\x06Vector\x12\x12\n\x06vector\x18\x01 \x03(\x01\x42\x02\x10\x01\"*\n\x0e\x45ncodedVectors\x12\x18\n\x07vectors\x18\x01 \x03(\x0b\x32\x07.Vector\"\x1f\n\x0cHelloRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2n\n\x0e\x45mbeddedEncode\x12\x35\n\x0e\x45ncodeSentence\x12\x10.EncodingRequest\x1a\x0f.EncodedVectors\"\x00\x12%\n\x05Hello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedded_encode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTOR'].fields_by_name['vector']._loaded_options = None
  _globals['_VECTOR'].fields_by_name['vector']._serialized_options = b'\020\001'
  _globals['_ENCODINGREQUEST']._serialized_start=25
  _globals['_ENCODINGREQUEST']._serialized_end=61
  _globals['_VECTOR']._serialized_start=63
  _globals['_VECTOR']._serialized_end=91
  _globals['_ENCODEDVECTORS']._serialized_start=93
  _globals['_ENCODEDVECTORS']._serialized_end=135
  _globals['_HELLOREQUEST']._serialized_start=137
  _globals['_HELLOREQUEST']._serialized_end=168
  _globals['_HELLOREPLY']._serialized_start=170
  _globals['_HELLOREPLY']._serialized_end=199
  _globals['_EMBEDDEDENCODE']._serialized_start=201
  _globals['_EMBEDDEDENCODE']._serialized_end=311
# @@protoc_insertion_point(module_scope)
